% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
  11pt,
]{article}
\usepackage{amsmath,amssymb}
\usepackage{lmodern}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same} % disable monospaced font for URLs
\hypersetup{
  pdftitle={Assignment 2: Group 45},
  pdfauthor={Daniel Engbert, Rik Timmer, Koen van der Pool},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{Assignment 2: Group 45}
\author{Daniel Engbert, Rik Timmer, Koen van der Pool}
\date{03 March 2023}

\begin{document}
\maketitle

Note: we made a function \texttt{checkNorm()} which prints a histogram,
qqplot, and p-value from the shapiro-wilk normality test. And we made a
function \texttt{printPval()} which simply prints a given p-value to 3
significant figures. We utilize both functions throughout this
assignment.

\hypertarget{exercise-1-trees}{%
\subsection{Exercise 1: Trees}\label{exercise-1-trees}}

\hypertarget{a}{%
\subsubsection{1 a)}\label{a}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{trees }\OtherTok{=} \FunctionTok{read.table}\NormalTok{(}\StringTok{"treeVolume.txt"}\NormalTok{, }\AttributeTok{header=}\NormalTok{T)}
\NormalTok{model }\OtherTok{=} \FunctionTok{lm}\NormalTok{(volume}\SpecialCharTok{\textasciitilde{}}\NormalTok{type, }\AttributeTok{data=}\NormalTok{trees)}
\FunctionTok{print}\NormalTok{(}\StringTok{"model coefficients:"}\NormalTok{); }\FunctionTok{summary}\NormalTok{(model)}\SpecialCharTok{$}\NormalTok{coefficients}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "model coefficients:"
\end{verbatim}

\begin{verbatim}
##             Estimate Std. Error t value Pr(>|t|)
## (Intercept)    30.17       2.54   11.88 4.68e-17
## typeoak         5.08       3.69    1.38 1.74e-01
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{res }\OtherTok{=} \FunctionTok{anova}\NormalTok{(model)}
\FunctionTok{sprintf}\NormalTok{(}\StringTok{"ANOVA p{-}value for type = \%.3f"}\NormalTok{, res[}\StringTok{"type"}\NormalTok{, }\StringTok{"Pr(\textgreater{}F)"}\NormalTok{])}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "ANOVA p-value for type = 0.174"
\end{verbatim}

The p-value \(0.174>0.05\) for the type in the ANOVA analysis of the
linear model, suggests there's insufficient evidence to reject the
\(H_0\) (that tree type influences volume).

\begin{verbatim}
## [1] "Shapiro-Wilk normality p-value for oak: 0.082"
\end{verbatim}

\includegraphics{hw2_files/figure-latex/unnamed-chunk-3-1.pdf}

\begin{verbatim}
## [1] "Shapiro-Wilk normality p-value for beech: 0.004"
\end{verbatim}

\begin{verbatim}
## [1] "oak mean volume = 35.250, beech mean volume = 30.171"
\end{verbatim}

We can split the data into two samples of tree volume based on the tree
types, and compare the means of the samples using a t-test to determine
whether, based on this data, there is a significant difference in mean
volume between the two tree types. As can be seen in the output of the
t-test \(0.166 > 0.05\), signifying once again that there is not enough
evidence to reject the null hypothesis that the means of the samples are
the same. This concurs with the results of the ANOVA.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{new\_oak }\OtherTok{=} \FunctionTok{data.frame}\NormalTok{(}\AttributeTok{type=}\StringTok{"oak"}\NormalTok{); new\_beech }\OtherTok{=} \FunctionTok{data.frame}\NormalTok{(}\AttributeTok{type =} \StringTok{"beech"}\NormalTok{)}
\NormalTok{pred1 }\OtherTok{=} \FunctionTok{predict}\NormalTok{(model, new\_oak); pred2 }\OtherTok{=} \FunctionTok{predict}\NormalTok{(model, new\_beech)}
\FunctionTok{sprintf}\NormalTok{(}\StringTok{"predicted volumes: oak = \%.3f, beech = \%.3f"}\NormalTok{, pred1, pred2)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "predicted volumes: oak = 35.250, beech = 30.171"
\end{verbatim}

\hypertarget{b}{%
\subsubsection{1 b)}\label{b}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{model }\OtherTok{=} \FunctionTok{lm}\NormalTok{(volume}\SpecialCharTok{\textasciitilde{}}\NormalTok{type}\SpecialCharTok{*}\NormalTok{diameter }\SpecialCharTok{+}\NormalTok{ height, }\AttributeTok{data=}\NormalTok{trees)}
\NormalTok{res }\OtherTok{=} \FunctionTok{anova}\NormalTok{(model)}
\FunctionTok{sprintf}\NormalTok{(}\StringTok{"ANOVA p{-}value for type:diameter = \%.3f"}\NormalTok{, res[}\StringTok{"type:diameter"}\NormalTok{, }\StringTok{"Pr(\textgreater{}F)"}\NormalTok{])}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "ANOVA p-value for type:diameter = 0.474"
\end{verbatim}

We built a linear model that added an interaction term between diameter
and type, the p-value \(0.474>0.05\) for this term suggests there's
insufficient evidence to reject the \(H_0\) (that the influence of
diameter on volume is the same for both tree types).

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{model }\OtherTok{=} \FunctionTok{lm}\NormalTok{(volume}\SpecialCharTok{\textasciitilde{}}\NormalTok{type}\SpecialCharTok{*}\NormalTok{height }\SpecialCharTok{+}\NormalTok{ diameter, }\AttributeTok{data=}\NormalTok{trees)}
\NormalTok{res }\OtherTok{=} \FunctionTok{anova}\NormalTok{(model)}
\FunctionTok{sprintf}\NormalTok{(}\StringTok{"ANOVA p{-}value for type:diameter = \%.3f"}\NormalTok{, res[}\StringTok{"type:height"}\NormalTok{, }\StringTok{"Pr(\textgreater{}F)"}\NormalTok{])}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "ANOVA p-value for type:diameter = 0.176"
\end{verbatim}

Now running another linear model that includes an interaction term
between height and type instead, the p-value \(0.176>0.05\) for this
term suggests there's insufficient evidence to reject the \(H_0\) (that
the influence of height on volume is the same for both tree types).

So based on the results from our two models above, there's insufficient
evidence to suggest that the influences of diameter and height aren't
similar for both tree types.

\hypertarget{c}{%
\subsubsection{1 c)}\label{c}}

We construct a linear model to investigate how diameter, height and type
influence volume.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{model }\OtherTok{=} \FunctionTok{lm}\NormalTok{(volume}\SpecialCharTok{\textasciitilde{}}\NormalTok{type}\SpecialCharTok{+}\NormalTok{height}\SpecialCharTok{+}\NormalTok{diameter, }\AttributeTok{data=}\NormalTok{trees)}
\FunctionTok{print}\NormalTok{(}\StringTok{"model coefficients:"}\NormalTok{); }\FunctionTok{summary}\NormalTok{(model)}\SpecialCharTok{$}\NormalTok{coefficients}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "model coefficients:"
\end{verbatim}

\begin{verbatim}
##             Estimate Std. Error t value Pr(>|t|)
## (Intercept)  -63.781     5.5129  -11.57 2.33e-16
## typeoak       -1.305     0.8779   -1.49 1.43e-01
## height         0.417     0.0752    5.55 8.42e-07
## diameter       4.698     0.1645   28.56 1.14e-34
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{print}\NormalTok{(}\StringTok{"anova:"}\NormalTok{); res }\OtherTok{=} \FunctionTok{anova}\NormalTok{(model); res}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "anova:"
\end{verbatim}

\begin{verbatim}
## Analysis of Variance Table
## 
## Response: volume
##           Df Sum Sq Mean Sq F value  Pr(>F)    
## type       1    380     380    36.1 1.6e-07 ***
## height     1   2239    2239   212.9 < 2e-16 ***
## diameter   1   8577    8577   815.6 < 2e-16 ***
## Residuals 55    578      11                    
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
\end{verbatim}

Based on the ANOVA p-values, type is not a significant predictor for
volume (p-value \(0.143 > 0.05\)), while height and diameter are
significant (p-values less than 0.05). Diameter and height are both
positively correlated with the volume, with diameter having the largest
contribution (coefficient) of the two.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# build better model where type isn\textquotesingle{}t considered}
\NormalTok{modelC }\OtherTok{=} \FunctionTok{lm}\NormalTok{(volume}\SpecialCharTok{\textasciitilde{}}\NormalTok{height}\SpecialCharTok{+}\NormalTok{diameter, }\AttributeTok{data=}\NormalTok{trees)}

\NormalTok{avgTree }\OtherTok{=} \FunctionTok{data.frame}\NormalTok{(}\AttributeTok{height=}\FunctionTok{mean}\NormalTok{(trees}\SpecialCharTok{$}\NormalTok{height), }\AttributeTok{diameter=}\FunctionTok{mean}\NormalTok{(trees}\SpecialCharTok{$}\NormalTok{diameter))}
\NormalTok{pred }\OtherTok{=} \FunctionTok{predict}\NormalTok{(modelC, avgTree)}
\FunctionTok{sprintf}\NormalTok{(}\StringTok{"predicted volume of average tree = \%.3f"}\NormalTok{, pred)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "predicted volume of average tree = 32.581"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# mean(trees$volume) \# this also gives the same result as expected}

\NormalTok{r2 }\OtherTok{=} \FunctionTok{summary}\NormalTok{(modelC)}\SpecialCharTok{$}\NormalTok{r.squared; ar2 }\OtherTok{=} \FunctionTok{summary}\NormalTok{(modelC)}\SpecialCharTok{$}\NormalTok{adj.r.squared}
\FunctionTok{sprintf}\NormalTok{(}\StringTok{"modelC: R\^{}2 = \%.3f, Adj. R\^{}2 = \%.3f"}\NormalTok{, r2, ar2)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "modelC: R^2 = 0.949, Adj. R^2 = 0.947"
\end{verbatim}

Using the resulting model, the volume of a tree with the average height
and diameter is predicted to be 32.581 .

\hypertarget{d}{%
\subsubsection{1 d)}\label{d}}

We propose to transform the data to create a new column that contains
the volume of a (theoretical) cylinder based on the tree's diameter and
height. (Note we omit tree type from the model as we found it to not be
a significant predictor above).

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# create predictor as cylinderical volume}
\NormalTok{trees}\SpecialCharTok{$}\NormalTok{cylinder }\OtherTok{=}\NormalTok{ trees}\SpecialCharTok{$}\NormalTok{diameter }\SpecialCharTok{*}\NormalTok{ pi }\SpecialCharTok{*}\NormalTok{ trees}\SpecialCharTok{$}\NormalTok{height}

\NormalTok{modelD }\OtherTok{=} \FunctionTok{lm}\NormalTok{(volume}\SpecialCharTok{\textasciitilde{}}\NormalTok{cylinder, }\AttributeTok{data=}\NormalTok{trees)}
\FunctionTok{print}\NormalTok{(}\StringTok{"model coefficients:"}\NormalTok{); }\FunctionTok{summary}\NormalTok{(modelD)}\SpecialCharTok{$}\NormalTok{coefficients}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "model coefficients:"
\end{verbatim}

\begin{verbatim}
##             Estimate Std. Error t value Pr(>|t|)
## (Intercept) -26.8923   2.058137   -13.1 8.67e-19
## cylinder      0.0179   0.000603    29.7 2.47e-36
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{r2 }\OtherTok{=} \FunctionTok{summary}\NormalTok{(modelD)}\SpecialCharTok{$}\NormalTok{r.squared; ar2 }\OtherTok{=} \FunctionTok{summary}\NormalTok{(modelD)}\SpecialCharTok{$}\NormalTok{adj.r.squared}
\FunctionTok{sprintf}\NormalTok{(}\StringTok{"model: R\^{}2 = \%.3f, Adj. R\^{}2 = \%.3f"}\NormalTok{, r2, ar2)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "model: R^2 = 0.939, Adj. R^2 = 0.938"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{print}\NormalTok{(}\StringTok{"ANOVA:"}\NormalTok{); }\FunctionTok{anova}\NormalTok{(model)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "ANOVA:"
\end{verbatim}

\begin{verbatim}
## Analysis of Variance Table
## 
## Response: volume
##           Df Sum Sq Mean Sq F value  Pr(>F)    
## type       1    380     380    36.1 1.6e-07 ***
## height     1   2239    2239   212.9 < 2e-16 ***
## diameter   1   8577    8577   815.6 < 2e-16 ***
## Residuals 55    578      11                    
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
\end{verbatim}

After constructing a linear model for predicting the actual tree volume
from our proposed cylindrical estimator, we see that the cylinder
variable is a significant predictor of volume (p \textless{} 0.05).
However the adjusted \(R^2\) values (and the regular \(R^2\) values) for
this model are less than that of the model in part c), so while cylinder
is a useful predictor, it's still inferior to using just the provided
height and diameter variables in the model.

\hypertarget{exercise-2-expenditure-on-criminal-activities}{%
\subsection{Exercise 2: Expenditure on criminal
activities}\label{exercise-2-expenditure-on-criminal-activities}}

\hypertarget{a-1}{%
\subsubsection{2 a)}\label{a-1}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{crimes }\OtherTok{=} \FunctionTok{read.table}\NormalTok{(}\StringTok{"expensescrime.txt"}\NormalTok{, }\AttributeTok{header=}\NormalTok{T)}
\FunctionTok{pairs}\NormalTok{(crimes[,}\SpecialCharTok{{-}}\DecValTok{1}\NormalTok{])}
\end{Highlighting}
\end{Shaded}

\includegraphics{hw2_files/figure-latex/unnamed-chunk-10-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{crimes}\SpecialCharTok{$}\NormalTok{state }\OtherTok{=} \FunctionTok{factor}\NormalTok{(crimes}\SpecialCharTok{$}\NormalTok{state)}


\NormalTok{model }\OtherTok{=} \FunctionTok{lm}\NormalTok{(expend}\SpecialCharTok{\textasciitilde{}}\NormalTok{bad}\SpecialCharTok{+}\NormalTok{crime}\SpecialCharTok{+}\NormalTok{lawyers}\SpecialCharTok{+}\NormalTok{employ}\SpecialCharTok{+}\NormalTok{pop, }\AttributeTok{data=}\NormalTok{crimes)}
\FunctionTok{summary}\NormalTok{(model)}\SpecialCharTok{$}\NormalTok{coefficients}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##              Estimate Std. Error t value Pr(>|t|)
## (Intercept) -299.1341   1.40e+02   -2.14  0.03817
## bad           -2.8319   1.24e+00   -2.28  0.02719
## crime          0.0324   2.81e-02    1.15  0.25534
## lawyers        0.0232   8.04e-03    2.89  0.00592
## employ         0.0230   7.46e-03    3.08  0.00354
## pop            0.0779   3.51e-02    2.22  0.03184
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{anova}\NormalTok{(model)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Analysis of Variance Table
## 
## Response: expend
##           Df   Sum Sq  Mean Sq F value  Pr(>F)    
## bad        1 49109638 49109638  965.16 < 2e-16 ***
## crime      1    44115    44115    0.87   0.357    
## lawyers    1 17237521 17237521  338.77 < 2e-16 ***
## employ     1  1590235  1590235   31.25 1.3e-06 ***
## pop        1   249704   249704    4.91   0.032 *  
## Residuals 45  2289716    50883                    
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{print}\NormalTok{(}\StringTok{\textquotesingle{}model 2:\textquotesingle{}}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "model 2:"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{model }\OtherTok{=} \FunctionTok{lm}\NormalTok{(expend}\SpecialCharTok{\textasciitilde{}}\NormalTok{crime}\SpecialCharTok{+}\NormalTok{bad}\SpecialCharTok{+}\NormalTok{lawyers}\SpecialCharTok{+}\NormalTok{employ}\SpecialCharTok{+}\NormalTok{pop, }\AttributeTok{data=}\NormalTok{crimes)}
\FunctionTok{summary}\NormalTok{(model)}\SpecialCharTok{$}\NormalTok{coefficients}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##              Estimate Std. Error t value Pr(>|t|)
## (Intercept) -299.1341   1.40e+02   -2.14  0.03817
## crime          0.0324   2.81e-02    1.15  0.25534
## bad           -2.8319   1.24e+00   -2.28  0.02719
## lawyers        0.0232   8.04e-03    2.89  0.00592
## employ         0.0230   7.46e-03    3.08  0.00354
## pop            0.0779   3.51e-02    2.22  0.03184
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{anova}\NormalTok{(model)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Analysis of Variance Table
## 
## Response: expend
##           Df   Sum Sq  Mean Sq F value  Pr(>F)    
## crime      1  7888219  7888219  155.03 3.5e-16 ***
## bad        1 41265535 41265535  811.00 < 2e-16 ***
## lawyers    1 17237521 17237521  338.77 < 2e-16 ***
## employ     1  1590235  1590235   31.25 1.3e-06 ***
## pop        1   249704   249704    4.91   0.032 *  
## Residuals 45  2289716    50883                    
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# sorting by population}
\CommentTok{\#crimes[order(crimes$pop, decreasing=TRUE),]}



\CommentTok{\#crimes}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{n }\OtherTok{=} \FunctionTok{length}\NormalTok{(crimes[,}\DecValTok{1}\NormalTok{])}
\NormalTok{dists }\OtherTok{=} \FunctionTok{cooks.distance}\NormalTok{(model)}
\FunctionTok{plot}\NormalTok{(}\DecValTok{1}\SpecialCharTok{:}\NormalTok{n, dists, }\AttributeTok{type=}\StringTok{"b"}\NormalTok{)}
\FunctionTok{abline}\NormalTok{(}\DecValTok{1}\NormalTok{, }\DecValTok{0}\NormalTok{, }\AttributeTok{col =} \StringTok{\textquotesingle{}red\textquotesingle{}}\NormalTok{) }\CommentTok{\# plot y=1 for reference}
\end{Highlighting}
\end{Shaded}

\includegraphics{hw2_files/figure-latex/unnamed-chunk-11-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# these are the indices into crimes that are cook\textquotesingle{}s points}
\NormalTok{dists[dists }\SpecialCharTok{\textgreater{}} \DecValTok{1}\NormalTok{]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##    5    8   35   44 
## 4.91 3.51 1.09 2.70
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# }\AlertTok{TODO}\CommentTok{: print state names}
\CommentTok{\#cooked = crimes[dists[dists \textgreater{} 1],]}
\CommentTok{\#cooked}

\CommentTok{\# investigating collinearity}
\FunctionTok{cor}\NormalTok{(crimes[,}\SpecialCharTok{{-}}\DecValTok{1}\NormalTok{])}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##         expend   bad crime lawyers employ   pop
## expend   1.000 0.834 0.334   0.968  0.977 0.953
## bad      0.834 1.000 0.373   0.832  0.871 0.920
## crime    0.334 0.373 1.000   0.375  0.311 0.275
## lawyers  0.968 0.832 0.375   1.000  0.966 0.934
## employ   0.977 0.871 0.311   0.966  1.000 0.971
## pop      0.953 0.920 0.275   0.934  0.971 1.000
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{res }\OtherTok{=} \FunctionTok{cor}\NormalTok{(crimes[,}\SpecialCharTok{{-}}\DecValTok{1}\NormalTok{])}
\CommentTok{\# using 0.8 as a threshold to help with visiblility}
\NormalTok{res[res }\SpecialCharTok{\textgreater{}=} \FloatTok{0.8}\NormalTok{] }\OtherTok{=}\NormalTok{ T; res[res }\SpecialCharTok{\textless{}=} \FloatTok{0.8}\NormalTok{] }\OtherTok{=}\NormalTok{ F; }
\NormalTok{res}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##         expend bad crime lawyers employ pop
## expend       1   1     0       1      1   1
## bad          1   1     0       1      1   1
## crime        0   0     1       0      0   0
## lawyers      1   1     0       1      1   1
## employ       1   1     0       1      1   1
## pop          1   1     0       1      1   1
\end{verbatim}

Based on the correlation coefficients, it appears that all the
explanatory variables are correlated, except for crime which has no
correlation with any of the other variables (its highest correlation
coefficient is 0.375). The other variables all have a correlation
coefficient of at least 0.832 between each other.

\hypertarget{b-1}{%
\subsubsection{2 b)}\label{b-1}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{evalModel }\OtherTok{=} \ControlFlowTok{function}\NormalTok{(model, name) \{}
  \FunctionTok{print}\NormalTok{(}\FunctionTok{sprintf}\NormalTok{(}\StringTok{"adding var \textquotesingle{}\%s\textquotesingle{}:"}\NormalTok{, name))}
  \FunctionTok{print}\NormalTok{(}\FunctionTok{summary}\NormalTok{(model)}\SpecialCharTok{$}\NormalTok{coefficients)}
\NormalTok{  r2 }\OtherTok{=} \FunctionTok{summary}\NormalTok{(model)}\SpecialCharTok{$}\NormalTok{r.squared; ar2 }\OtherTok{=} \FunctionTok{summary}\NormalTok{(model)}\SpecialCharTok{$}\NormalTok{adj.r.squared}
  \FunctionTok{sprintf}\NormalTok{(}\StringTok{"model: R\^{}2 = \%.3f"}\NormalTok{, r2)}
\NormalTok{\}}

\FunctionTok{evalModel}\NormalTok{(}\FunctionTok{lm}\NormalTok{(expend}\SpecialCharTok{\textasciitilde{}}\NormalTok{bad, }\AttributeTok{data=}\NormalTok{crimes), }\AttributeTok{name=}\StringTok{"bad"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "adding var 'bad':"
##             Estimate Std. Error t value Pr(>|t|)
## (Intercept)    126.7     114.86     1.1 2.75e-01
## bad             13.3       1.26    10.6 2.80e-14
\end{verbatim}

\begin{verbatim}
## [1] "model: R^2 = 0.696"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{evalModel}\NormalTok{(}\FunctionTok{lm}\NormalTok{(expend}\SpecialCharTok{\textasciitilde{}}\NormalTok{crime, }\AttributeTok{data=}\NormalTok{crimes), }\AttributeTok{name=}\StringTok{"crime"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "adding var 'crime':"
##             Estimate Std. Error t value Pr(>|t|)
## (Intercept) -531.039    577.166   -0.92   0.3620
## crime          0.287      0.116    2.48   0.0165
\end{verbatim}

\begin{verbatim}
## [1] "model: R^2 = 0.112"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{evalModel}\NormalTok{(}\FunctionTok{lm}\NormalTok{(expend}\SpecialCharTok{\textasciitilde{}}\NormalTok{lawyers, }\AttributeTok{data=}\NormalTok{crimes), }\AttributeTok{name=}\StringTok{"lawyers"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "adding var 'lawyers':"
##             Estimate Std. Error t value Pr(>|t|)
## (Intercept) -59.6120    53.7994   -1.11 2.73e-01
## lawyers       0.0704     0.0026   27.06 4.02e-31
\end{verbatim}

\begin{verbatim}
## [1] "model: R^2 = 0.937"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{evalModel}\NormalTok{(}\FunctionTok{lm}\NormalTok{(expend}\SpecialCharTok{\textasciitilde{}}\NormalTok{employ, }\AttributeTok{data=}\NormalTok{crimes), }\AttributeTok{name=}\StringTok{"employ"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "adding var 'employ':"
##              Estimate Std. Error t value Pr(>|t|)
## (Intercept) -116.7052   47.06076   -2.48 1.66e-02
## employ         0.0468    0.00147   31.87 2.03e-34
\end{verbatim}

\begin{verbatim}
## [1] "model: R^2 = 0.954"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{evalModel}\NormalTok{(}\FunctionTok{lm}\NormalTok{(expend}\SpecialCharTok{\textasciitilde{}}\NormalTok{pop, }\AttributeTok{data=}\NormalTok{crimes), }\AttributeTok{name=}\StringTok{"pop"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "adding var 'pop':"
##             Estimate Std. Error t value Pr(>|t|)
## (Intercept) -188.767   69.67628   -2.71 9.27e-03
## pop            0.217    0.00992   21.90 5.83e-27
\end{verbatim}

\begin{verbatim}
## [1] "model: R^2 = 0.907"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# employ has highest adj. R\^{}2 (0.955) and is significant}
\FunctionTok{print}\NormalTok{(}\StringTok{"****round2****"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "****round2****"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{evalModel}\NormalTok{(}\FunctionTok{lm}\NormalTok{(expend}\SpecialCharTok{\textasciitilde{}}\NormalTok{employ}\SpecialCharTok{+}\NormalTok{bad, }\AttributeTok{data=}\NormalTok{crimes), }\AttributeTok{name=}\StringTok{"bad"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "adding var 'bad':"
##              Estimate Std. Error t value Pr(>|t|)
## (Intercept) -116.4498   46.96559   -2.48 1.67e-02
## employ         0.0497    0.00299   16.63 1.48e-21
## bad           -1.0898    0.99481   -1.10 2.79e-01
\end{verbatim}

\begin{verbatim}
## [1] "model: R^2 = 0.955"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{evalModel}\NormalTok{(}\FunctionTok{lm}\NormalTok{(expend}\SpecialCharTok{\textasciitilde{}}\NormalTok{employ}\SpecialCharTok{+}\NormalTok{crime, }\AttributeTok{data=}\NormalTok{crimes), }\AttributeTok{name=}\StringTok{"crime"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "adding var 'crime':"
##              Estimate Std. Error t value Pr(>|t|)
## (Intercept) -248.3631   1.32e+02   -1.89 6.50e-02
## employ         0.0463   1.54e-03   30.01 9.37e-33
## crime          0.0296   2.76e-02    1.07 2.89e-01
\end{verbatim}

\begin{verbatim}
## [1] "model: R^2 = 0.955"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{evalModel}\NormalTok{(}\FunctionTok{lm}\NormalTok{(expend}\SpecialCharTok{\textasciitilde{}}\NormalTok{employ}\SpecialCharTok{+}\NormalTok{lawyers, }\AttributeTok{data=}\NormalTok{crimes), }\AttributeTok{name=}\StringTok{"lawyers"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "adding var 'lawyers':"
##              Estimate Std. Error t value Pr(>|t|)
## (Intercept) -110.6588   42.56735   -2.60 1.24e-02
## employ         0.0297    0.00511    5.81 4.89e-07
## lawyers        0.0269    0.00776    3.46 1.13e-03
\end{verbatim}

\begin{verbatim}
## [1] "model: R^2 = 0.963"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{evalModel}\NormalTok{(}\FunctionTok{lm}\NormalTok{(expend}\SpecialCharTok{\textasciitilde{}}\NormalTok{employ}\SpecialCharTok{+}\NormalTok{pop, }\AttributeTok{data=}\NormalTok{crimes), }\AttributeTok{name=}\StringTok{"pop"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "adding var 'pop':"
##              Estimate Std. Error t value Pr(>|t|)
## (Intercept) -126.5921   50.21637  -2.521 1.51e-02
## employ         0.0433    0.00616   7.026 6.72e-09
## pop            0.0174    0.02930   0.594 5.55e-01
\end{verbatim}

\begin{verbatim}
## [1] "model: R^2 = 0.954"
\end{verbatim}

In the 1st round of the ``step up'' method we found ``employ'' to lead
to the largest \(R^2\) model, while still being statistically
significant.

In the 2nd round of the ``step up'' method, ``lawyers'' was found to
lead to the largest increase in \(R^2\) while still being statistically
significant, however the increase in \(R^2\) was only
\(0.963-0.954=0.009\), which is quite low, so we don't deem it worth
adding to the model.

The result of the ``step up'' method suggesting the model should only
have one explanatory variable (``employ'') is not surprising as we
showed further above that all the variables (except for ``crime'') are
collinear.

\hypertarget{c-1}{%
\subsubsection{2 c)}\label{c-1}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{model }\OtherTok{=} \FunctionTok{lm}\NormalTok{(expend}\SpecialCharTok{\textasciitilde{}}\NormalTok{employ, }\AttributeTok{data=}\NormalTok{crimes) }\CommentTok{\# result of part 2b}
\NormalTok{state }\OtherTok{=} \FunctionTok{data.frame}\NormalTok{(}\AttributeTok{bad=}\DecValTok{50}\NormalTok{, }\AttributeTok{crime=}\DecValTok{5000}\NormalTok{, }\AttributeTok{lawyers=}\DecValTok{5000}\NormalTok{, }\AttributeTok{employ=}\DecValTok{5000}\NormalTok{, }\AttributeTok{pop=}\DecValTok{5000}\NormalTok{)}
\FunctionTok{predict}\NormalTok{(model, state, }\AttributeTok{interval=}\StringTok{"prediction"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   fit  lwr upr
## 1 117 -407 642
\end{verbatim}

The predicted interval \([-407, 642]\) can be improved by adjusting it
to \([0, 642]\) as we know the expenditure must be a positive number. So
we're 95\% confident that the expenditure by this hypothetical state
would be between \$0 and \$642,000.

\hypertarget{d-1}{%
\subsubsection{2 d)}\label{d-1}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{x}\OtherTok{=}\FunctionTok{as.matrix}\NormalTok{(crimes[,}\SpecialCharTok{{-}}\DecValTok{1}\NormalTok{])}
\NormalTok{x}\OtherTok{=}\NormalTok{x[,}\SpecialCharTok{{-}}\DecValTok{1}\NormalTok{]}
\NormalTok{y}\OtherTok{=}\NormalTok{crimes[,}\DecValTok{2}\NormalTok{]}
\NormalTok{x}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##         bad crime lawyers employ   pop
##  [1,]   5.1  5877    1749   2796   525
##  [2,]  34.4  3942    6679  13999  4083
##  [3,]  19.2  3585    3741   7227  2388
##  [4,]  31.3  7116    7535  14755  3386
##  [5,] 336.2  6518   82001 118149 27663
##  [6,]  25.7  6919   11174  12556  3296
##  [7,]  43.5  3705   11397  14798  3211
##  [8,]  23.3  8339   28399   7925   622
##  [9,]  10.6  4961    1597   3230   644
## [10,] 177.9  7574   30444  57310 12023
## [11,] 129.2  5110   13652  25848  6222
## [12,]  10.8  5201    2787   3886  1083
## [13,]  17.7  3943    6182   9309  2834
## [14,]   5.8  3908    2031   3363   998
## [15,] 113.0  5303   37873  57748 11582
## [16,]  55.3  3914    9499  19647  5531
## [17,]  23.8  4375    5555   9726  2476
## [18,]  27.9  2947    7017  13480  3727
## [19,]  52.7  5564   10569  21184  4461
## [20,]  37.8  4758   22154  26048  5855
## [21,]  92.0  5373   12866  22541  4535
## [22,]   6.3  3672    2528   4340  1187
## [23,] 107.2  6366   20445  36632  9200
## [24,]  38.6  4134   11343  13159  4246
## [25,]  44.9  4366   12439  20260  5103
## [26,]  18.9  3266    4270   8463  2625
## [27,]   4.9  4549    2006   3211   809
## [28,]  80.2  4121    9265  24843  6413
## [29,]   2.4  2679    1290   1997   672
## [30,]  13.7  3695    4289   5820  1594
## [31,]   4.8  3252    2139   4034  1057
## [32,]  79.2  5094   23301  49346  7672
## [33,]   8.9  6486    3164   7413  1500
## [34,]  11.4  6575    2276   5528  1007
## [35,] 176.7  5589   72575 111518 17825
## [36,]  96.0  4187   27191  38404 10784
## [37,]  32.4  5425    8302  13167  3272
## [38,]  31.2  6730    7385   9858  2724
## [39,] 101.9  3037   27798  46200 11936
## [40,]   9.2  4723    2527   3774   986
## [41,]  34.5  4841    5021  13177  3425
## [42,]   3.9  2641    1230   2396   709
## [43,]  45.2  4167    8782  18190  4855
## [44,] 370.1  6569   39028  65488 16789
## [45,]  10.0  5317    3446   5715  1680
## [46,]  40.5  3779   13390  25720  5904
## [47,]   6.2  3888    1372   1969   548
## [48,]  60.7  6529   11507  17020  4538
## [49,]  36.6  4017   10316  19911  4807
## [50,]   7.2  2253    2835   5079  1897
## [51,]   3.1  4015    1116   2558   490
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{train}\OtherTok{=}\FunctionTok{sample}\NormalTok{(}\DecValTok{1}\SpecialCharTok{:}\FunctionTok{nrow}\NormalTok{(x),}\FloatTok{0.67}\SpecialCharTok{*}\FunctionTok{nrow}\NormalTok{(x))}
\NormalTok{x.train}\OtherTok{=}\NormalTok{x[train,]; y.train}\OtherTok{=}\NormalTok{y[train]}
\NormalTok{x.test}\OtherTok{=}\NormalTok{x[}\SpecialCharTok{{-}}\NormalTok{train,]; y.test }\OtherTok{=}\NormalTok{ y[}\SpecialCharTok{{-}}\NormalTok{train] }

\NormalTok{lm.model}\OtherTok{=}\FunctionTok{lm}\NormalTok{(expend}\SpecialCharTok{\textasciitilde{}}\NormalTok{bad}\SpecialCharTok{+}\NormalTok{crime}\SpecialCharTok{+}\NormalTok{lawyers}\SpecialCharTok{+}\NormalTok{employ}\SpecialCharTok{+}\NormalTok{pop,}\AttributeTok{data=}\NormalTok{crimes,}\AttributeTok{subset=}\NormalTok{train)}
\NormalTok{y.predict.lm}\OtherTok{=}\FunctionTok{predict}\NormalTok{(lm.model,}\AttributeTok{newdata=}\NormalTok{crimes[}\SpecialCharTok{{-}}\NormalTok{train,])}
\NormalTok{mse.lm}\OtherTok{=}\FunctionTok{mean}\NormalTok{((y.test}\SpecialCharTok{{-}}\NormalTok{y.predict.lm)}\SpecialCharTok{\^{}}\DecValTok{2}\NormalTok{); mse.lm}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 36931
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{mse.lm}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 36931
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(glmnet) }
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Loading required package: Matrix
\end{verbatim}

\begin{verbatim}
## Loaded glmnet 4.1-6
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{lasso.model}\OtherTok{=}\FunctionTok{glmnet}\NormalTok{(x.train,y.train,}\AttributeTok{alpha=}\DecValTok{1}\NormalTok{)}
\NormalTok{lasso.cv}\OtherTok{=}\FunctionTok{cv.glmnet}\NormalTok{(x.train,y.train,}\AttributeTok{alpha=}\DecValTok{1}\NormalTok{,}\AttributeTok{type.measure=}\StringTok{"mse"}\NormalTok{,}\AttributeTok{nfolds=}\DecValTok{5}\NormalTok{)}

\FunctionTok{plot}\NormalTok{(lasso.model,}\AttributeTok{label=}\NormalTok{T,}\AttributeTok{xvar=}\StringTok{"lambda"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{hw2_files/figure-latex/unnamed-chunk-14-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{plot}\NormalTok{(lasso.cv) }
\end{Highlighting}
\end{Shaded}

\includegraphics{hw2_files/figure-latex/unnamed-chunk-14-2.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{lambda.min}\OtherTok{=}\NormalTok{lasso.cv}\SpecialCharTok{$}\NormalTok{lambda.min; lambda}\FloatTok{.1}\NormalTok{se}\OtherTok{=}\NormalTok{lasso.cv}\SpecialCharTok{$}\NormalTok{lambda}\FloatTok{.1}\NormalTok{se; }
\NormalTok{lambda.min; lambda}\FloatTok{.1}\NormalTok{se }
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 36
\end{verbatim}

\begin{verbatim}
## [1] 211
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{coef}\NormalTok{(lasso.model,}\AttributeTok{s=}\NormalTok{lasso.cv}\SpecialCharTok{$}\NormalTok{lambda.min) }
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 6 x 1 sparse Matrix of class "dgCMatrix"
##                   s1
## (Intercept) -96.4352
## bad           .     
## crime         .     
## lawyers       0.0226
## employ        0.0291
## pop           0.0146
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{coef}\NormalTok{(lasso.model,}\AttributeTok{s=}\NormalTok{lasso.cv}\SpecialCharTok{$}\NormalTok{lambda}\FloatTok{.1}\NormalTok{se) }
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 6 x 1 sparse Matrix of class "dgCMatrix"
##                  s1
## (Intercept) 52.9133
## bad          .     
## crime        .     
## lawyers      0.0176
## employ       0.0291
## pop          .
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{lasso.pred1}\OtherTok{=}\FunctionTok{predict}\NormalTok{(lasso.model,}\AttributeTok{s=}\NormalTok{lambda.min,}\AttributeTok{newx=}\NormalTok{x.test) }
\NormalTok{lasso.pred2}\OtherTok{=}\FunctionTok{predict}\NormalTok{(lasso.model,}\AttributeTok{s=}\NormalTok{lambda}\FloatTok{.1}\NormalTok{se,}\AttributeTok{newx=}\FunctionTok{as.matrix}\NormalTok{(x.test))}
\NormalTok{mse1.lasso}\OtherTok{=}\FunctionTok{mean}\NormalTok{((y.test}\SpecialCharTok{{-}}\NormalTok{lasso.pred1)}\SpecialCharTok{\^{}}\DecValTok{2}\NormalTok{); mse1.lasso}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 20407
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{mse2.lasso}\OtherTok{=}\FunctionTok{mean}\NormalTok{((y.test}\SpecialCharTok{{-}}\NormalTok{lasso.pred2)}\SpecialCharTok{\^{}}\DecValTok{2}\NormalTok{); mse2.lasso}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 15809
\end{verbatim}

As we can see from the lambdas calculated by the model above, for the
minimum error, the relevant variables are bad, crime, lawyers, and
employ. To obtain a reduced model that is within one standard error of
the minimum, we can take into account only bad, lawyers, and employ. In
general the model is very similar to the one in b). While in b), the
variables that were collinear could have been added to the model to
improve the R\^{}2, we chose not to do so because the improvement was
marginal. The lasso model does something similar, in that it selects one
of the aforementioned variables as the primary factor (which has a large
coefficient), and the other (believed to be collinear) variables that
are shown as relevant by the lasso model have very small coefficients,
because as we saw, they had very little effect on the R\^{}2 in b).

\hypertarget{exercise-3-titanic}{%
\subsection{Exercise 3: Titanic}\label{exercise-3-titanic}}

\hypertarget{a-2}{%
\subsubsection{3 a)}\label{a-2}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{titanic }\OtherTok{=} \FunctionTok{read.table}\NormalTok{(}\StringTok{"titanic.txt"}\NormalTok{, }\AttributeTok{header=}\NormalTok{T)}
\CommentTok{\#titanic}
\end{Highlighting}
\end{Shaded}

\hypertarget{exercise-4-military-coups}{%
\subsection{Exercise 4: Military
Coups}\label{exercise-4-military-coups}}

\hypertarget{a-3}{%
\subsubsection{4 a)}\label{a-3}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{coups }\OtherTok{=} \FunctionTok{read.table}\NormalTok{(}\StringTok{"coups.txt"}\NormalTok{, }\AttributeTok{header=}\NormalTok{T)}
\CommentTok{\#coups}
\end{Highlighting}
\end{Shaded}


\end{document}
